
-- +migrate Up
CREATE TABLE IF NOT EXISTS users(
    id INTEGER PRIMARY KEY AUTO_INCREMENT,
    Name VARCHAR (50) NOT NULL,
    Email VARCHAR (100) NOT NULL,
    Password VARCHAR (50) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP NULL 
);

-- +migrate Down
DROP TABLE IF EXISTS users;