
-- +migrate Up
CREATE TABLE IF NOT EXISTS todos(
    id INTEGER PRIMARY KEY AUTO_INCREMENT,
    Title VARCHAR (150) NOT NULL,
    Content VARCHAR (400) NOT NULL,
    Status INTEGER NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP NULL 
);

-- +migrate Down
DROP TABLE IF EXISTS todos;
