test:
  dialect: mysql
  datasource: ${MYSQL_USER}:${MYSQL_ROOT_PASSWORD}@tcp(${MYSQL_HOST}:${MYSQL_PORT})/${MYSQL_TEST_DATABASE}?parseTime=true
  dir: migrations/development
development:
  dialect: mysql
  datasource: ${MYSQL_USER}:${MYSQL_ROOT_PASSWORD}@tcp(${MYSQL_HOST}:${MYSQL_PORT})/${MYSQL_DATABASE}?parseTime=true
  dir: migrations/development